#!/usr/bin/env python3
"""Write the list of file_ids to exclude from the merged datasets.

A call is excluded when its English translation fails the hard checks in
translate.check_translation -- in practice, decoder degeneration: the translator
looped on a token ("hello hello hello ...") until it hit max_new_tokens, so the
call was never actually translated past the point the loop began.

The exclusion is applied to BOTH languages by build_merged_data.py. Dropping the
call from English alone would leave the two corpora covering different sets of
calls, and an Arabic-vs-English difference would no longer be attributable to
language. Discarding a sound Arabic transcript is the price of that control.

The list is a file rather than a check performed inside build_merged_data.py so
that it is auditable, diffable and version-controllable: the exact set of calls
removed from a published result should not depend on which version of a heuristic
happened to run that day. Regenerate it whenever the translations change::

    python make_exclusion_list.py \\
        --pred translations/qwen2.5-72b-instruct.jsonl \\
        --out excluded_file_ids.txt
    python build_merged_data.py --exclude excluded_file_ids.txt
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from translate import check_translation, hard_flags, looping_ratio


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--pred", type=Path,
                   default=Path("translations/qwen2.5-72b-instruct.jsonl"))
    p.add_argument("--out", type=Path, default=Path("excluded_file_ids.txt"))
    return p.parse_args()


def main() -> int:
    args = parse_args()
    records = [json.loads(l) for l in args.pred.open(encoding="utf-8") if l.strip()]

    bad: list[tuple[str, list[str], float]] = []
    for rec in records:
        flags = check_translation(rec["arabic"], rec["english"])
        hard = hard_flags(flags)
        if hard:
            bad.append((rec["file_id"], hard, looping_ratio(rec["english"])))
    bad.sort()

    lines = [
        "# file_ids excluded from the merged datasets (both languages).",
        "# Generated by make_exclusion_list.py -- do not edit by hand.",
        f"# Source: {args.pred}",
        f"# {len(bad)} of {len(records)} translations fail the hard checks.",
        "#",
        "# file_id    reason",
    ]
    for fid, hard, loop in bad:
        lines.append(f"{fid}  # {','.join(hard)}  en_loop={loop:.0%}")
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(bad)}/{len(records)} translations fail the hard checks")
    print(f"Wrote {args.out}")
    print(f"\nApply it with:\n  python build_merged_data.py --exclude {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
